### ISSUE TITLE
游戏闪退报错 game crash

### ISSUE THREAD

**Issue by fjf010223** [Cyrillya/ConciseModList#1]
只多开启了这一个mod后，游戏崩溃，再打开游戏后进入模组列表就崩溃

System.Exception: 出现错误嘞
   at CalamityCN.Systems.ColorDisplayName.DrawHook(DrawDelegate orig, Object uiModItem, SpriteBatch sb) in CalamityCN\Systems\ColorDisplayName.cs:line 85
   at Terraria.GameContent.UI.Elements.UIList.UIInnerList.DrawChildren(SpriteBatch spriteBatch) in tModLoader\Terraria\GameContent\UI\Elements\UIList.cs:line 25
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch) in tModLoader\Terraria\UI\UIElement.cs:line 196
   at Terraria.UI.UIElement.DrawChildren(SpriteBatch spriteBatch) in tModLoader\Terraria\UI\UIElement.cs:line 130
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch) in tModLoader\Terraria\UI\UIElement.cs:line 196
   at Terraria.UI.UIElement.DrawChildren(SpriteBatch spriteBatch) in tModLoader\Terraria\UI\UIElement.cs:line 130
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch) in tModLoader\Terraria\UI\UIElement.cs:line 196
   at Terraria.UI.UIElement.DrawChildren(SpriteBatch spriteBatch) in tModLoader\Terraria\UI\UIElement.cs:line 130
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch) in tModLoader\Terraria\UI\UIElement.cs:line 196
   at Terraria.UI.UIElement.DrawChildren(SpriteBatch spriteBatch) in tModLoader\Terraria\UI\UIElement.cs:line 130
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch) in tModLoader\Terraria\UI\UIElement.cs:line 196
   at Terraria.ModLoader.UI.UIMods.Draw(SpriteBatch spriteBatch) in tModLoader\Terraria\ModLoader\UI\UIMods.cs:line 359
   at Terraria.Main.DrawMenu(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 39882
   at DMD<Terraria.Main::DoDraw>(Main this, GameTime gameTime)
   at GravityDontFlipScreen.GravityFlipSystem.Main_DoDraw(orig_DoDraw orig, Main self, GameTime gameTime) in GravityDontFlipScreen\GravityFlipSystem.cs:line 116
   at Terraria.Main.Draw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 48723
   at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 562
   at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 878
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 419
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 227
[19:48:40.024] [Main Thread/DEBUG] [TerrariaSteamClient]: Send: shutdown

**Comment by Cyrillya** [comment]
修复了，你可以更新之后再试一下
